name: Build posts.json & RSS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Build posts.json and rss.xml
        env:
          SITE_URL: https://sivashankarg.github.io/test-site
        run: python .github/scripts/build_index.py
      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: actions@github.com
          message: "chore: rebuild posts.json & rss.xml"
          add: "posts.json rss.xml"
